float32 target_tx
float32 target_ty
float32 target_tz
float32 actual_tx
float32 actual_ty
float32 actual_tz

float32 delta_tx
float32 delta_ty
float32 delta_tz

float32 target_qx
float32 target_qy
float32 target_qz
float32 target_qw
float32 actual_qx
float32 actual_qy
float32 actual_qz
float32 actual_qw

float32 delta_qx
float32 delta_qy
float32 delta_qz
float32 delta_qw

float32 target_rr
float32 target_rp
float32 target_ry
float32 actual_rr
float32 actual_rp
float32 actual_ry

float32 delta_rr
float32 delta_rp
float32 delta_ry
